### ISSUE TITLE
Set environment url on deployment jobs

### ISSUE THREAD

**Issue by amilochau** [amilochau/github-actions#134]
we should set environment URL on deployment jobs, to get links to the deployed application.

```yaml
    environment:
      name: DEV
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
```
