### ISSUE TITLE
Use .NET version in .NET GitHub Actions

### ISSUE THREAD

**Issue by amilochau** [amilochau/github-actions#73]
As we do with Node.js, we should get the .NET version as an Actions input, and use the following task:

```yaml
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.NUGET_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
